# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_description', models.TextField(blank=True, max_length=1024, null=True)),
                ('p_datetime', models.DateTimeField(db_index=True)),
                ('p_longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('p_latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('p_elevation', models.IntegerField()),
            ],
        ),
    ]
